"""voice publication fields

Revision ID: 170405a66b05
Revises: 9e38a04b079d
Create Date: 2019-08-17 17:55:55.434955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170405a66b05'
down_revision = '9e38a04b079d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('post_message_id', sa.Integer(), nullable=True))
    op.add_column('voice', sa.Column('title_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'title_message_id')
    op.drop_column('voice', 'post_message_id')
    # ### end Alembic commands ###
