"""create chat table

Revision ID: 1a39567fb2d3
Revises: 75586da3f235
Create Date: 2019-08-16 22:45:19.650948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a39567fb2d3'
down_revision = '75586da3f235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_telegram_chat_id'), 'chat', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_telegram_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
