"""add sender fk

Revision ID: 30e01d46a696
Revises: af83b1c55620
Create Date: 2019-08-16 23:45:17.444601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e01d46a696'
down_revision = 'af83b1c55620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'voice', 'chat', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice', type_='foreignkey')
    # ### end Alembic commands ###
