"""add voice search title

Revision ID: 6ef75cd1623f
Revises: 170405a66b05
Create Date: 2019-08-17 18:12:32.884334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef75cd1623f'
down_revision = '170405a66b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('search_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'search_title')
    # ### end Alembic commands ###
