"""ping migration

Revision ID: 75586da3f235
Revises: 
Create Date: 2019-08-16 22:39:25.972460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75586da3f235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
