"""add voice state

Revision ID: 76a3d088a731
Revises: a3bd6cf10d35
Create Date: 2019-08-17 15:28:56.634387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a3d088a731'
down_revision = 'a3bd6cf10d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'status')
    # ### end Alembic commands ###
