"""add voice table

Revision ID: af83b1c55620
Revises: f56265a51b10
Create Date: 2019-08-16 23:42:00.176566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af83b1c55620'
down_revision = 'f56265a51b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('author_first_name', sa.String(length=255), nullable=True),
    sa.Column('author_last_name', sa.String(length=255), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice')
    # ### end Alembic commands ###
