"""add voice title

Revision ID: d48a7e4e71bf
Revises: 30e01d46a696
Create Date: 2019-08-17 00:04:16.295170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48a7e4e71bf'
down_revision = '30e01d46a696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'title')
    # ### end Alembic commands ###
