"""add voice is_public field

Revision ID: f469b8ec99fd
Revises: 76a3d088a731
Create Date: 2019-08-17 16:07:27.982271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f469b8ec99fd'
down_revision = '76a3d088a731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'is_public')
    # ### end Alembic commands ###
