"""add chat state column

Revision ID: f56265a51b10
Revises: 1a39567fb2d3
Create Date: 2019-08-16 23:25:37.453813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56265a51b10'
down_revision = '1a39567fb2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'state')
    # ### end Alembic commands ###
